# Generated by Django 2.1.4 on 2018-12-17 05:38

from django.db import migrations, models
import django.db.models.deletion
import ok.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('birth_day', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('passport', models.ImageField(upload_to=ok.models.image_folder, verbose_name='Скан паспорта')),
                ('registration', models.ImageField(upload_to=ok.models.image_folder, verbose_name='Скан прописки')),
                ('inn', models.ImageField(upload_to=ok.models.image_folder, verbose_name='ИНН')),
                ('inps', models.ImageField(upload_to=ok.models.image_folder, verbose_name='ИНПС')),
                ('slug', models.SlugField()),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.Citizen')),
            ],
        ),
    ]
