# Generated by Django 2.1.4 on 2018-12-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizen',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Личные данные сотрудника', 'verbose_name_plural': 'Личные данные сотрудников'},
        ),
    ]
