# Generated by Django 2.1.4 on 2018-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0003_auto_20181217_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
