# Generated by Django 2.1.4 on 2018-12-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0004_auto_20181217_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
    ]
