# Generated by Django 2.1.4 on 2018-12-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ok', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Оклад')),
                ('slug', models.SlugField(blank=True)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.Category', verbose_name='Отдел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok.Employee', verbose_name='СОтрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
